### ISSUE TITLE
How to find Block Volume from SDK on host

### ISSUE THREAD

**Issue by gcstang** [oracle/oci-go-sdk#128]
If I have an iSCSI Block Volume attached to a host how can I find the proper Block Volume?

Infrastructure:
1. Create compute instance
2. Add block volume(BV) to it via iSCSI
3. Run Attach commands, etc.. to mount BV to the compute instance.

Find Block Volume on Host using SDK
1. Determine the host we're on by finding the hostname
2. ListInstances and filter by hostname, pull instanceId
3. ListVolumeAttachments for instanceId
4. Find Volume Id by ???

I have several pieces of information on the compute instance but nothing that maps me back to a Volume Id that I'm aware of outside of setting a FreeForm tag and searching for it.

Is there another way to retrieve the Block Volume Id when all you have is the information on the Compute instance?

**Comment by fullymad** [comment]
Being new to OCI (and OCI SDK), I may not have understood your problem fully, but I am able to get the volume ID of attached volumes by providing the compartment ID and instance ID in the ListVolumeAttachments request. Here is the client code (with IDs hard-coded for simplicity). I did the same steps to attach and mount BV before calling the API.

package main

import (
	"context"
	"github.com/oracle/oci-go-sdk/common"
	"github.com/oracle/oci-go-sdk/core"
	"github.com/oracle/oci-go-sdk/example/helpers"
	"log"
)

func main() {
	cl, cl_err := core.NewComputeClientWithConfigurationProvider(common.DefaultConfigProvider())
	helpers.FatalIfError(cl_err)

	ctx := context.Background()

	request := core.ListVolumeAttachmentsRequest{}
	request.CompartmentId = common.String("ocid1.tenancy.oc1…”……..)
	request.InstanceId = common.String("ocid1.instance.oc1.iad……….”)

	response, cl_err := cl.ListVolumeAttachments(ctx, request)
	helpers.FatalIfError(cl_err)

	for i, vol_attached := range response.Items {
		log.Printf("Volume %d: %s\n", (i + 1), *vol_attached.GetVolumeId())
	}
} //end main

**Comment by gcstang** [comment]
@fullymad I can get them that way but I'm attempting to work back from the system to the unique id of a mounted block volume.

i.e. 
I have the instance hostname so I can list my instances and find it in the list.
I can then list the attachments on that instance which gives me the volumes.
However there is nothing to figure out which mount on the system maps to the specific block volume.

The only way would be to tag the block volume however if that is not done during an upgrade or when a new volume is attached it wouldn't work.  

I need some way to map back from the instance (actual VM not instance id) to a specific block volume that is mounted on the instance. 

i.e.
Hostname: instance1
Has attachments, lets say 4 block volumes.
Block Vol 1 -> /u01 .   UUID (is some random number)
BV2 -> /u03 .   UUID (is some random number)
BV3 -> /u04 .   UUID (is some random number)
BV4 -> /u07 .   UUID (is some random number)
if a program is running from the instance how can it back trace to the correct Block Volume Id?
Say I want to backup just the mount at /u03 for example.

**Comment by fullymad** [comment]
@gcstang Thanks for the clarification. You say "However there is nothing to figure out which mount on the system maps to the specific block volume". If I understand correctly that the idea is to get the block volume ID for a given mount point, I can think of a potential way (may not be the recommended way though!!).

1. Running the command "oci-iscsi-config -s" lists all the attached iSCSI devices with their mount point, IQN, etc. The output of this command can be parsed to get the IQN for a given mount point. This value will be used in step 2 below.

2. In my earlier program, the for loop can be changed as below. (Note: My type assertion below does not check if the returned type is IScsiVolumeAttachement but that check can be easily added).

**var iscsi core.IScsiVolumeAttachment**
for i, vol_attached := range response.Items {
	log.Printf("Volume %d: %s\n", (i + 1), *vol_attached.GetVolumeId())
	**iscsi = vol_attached.(core.IScsiVolumeAttachment)**
	log.Printf("Iqn: %s\n", *iscsi.Iqn)
}

Instead of printing IQN, it can be compared with the input IQN from step 1 and if matched, the corresponding volume is the one at the given mount point.

**Comment by gcstang** [comment]
@fullymad that works! 

Thank you for your help.

**Comment by jasonyin** [comment]
I am closing this issue.
